version: 2

orbs:
  node: circleci/node@5.0.2
  gh: circleci/github-cli@2.0

jobs:
  publish-to-npm:
    docker:
      - image: node:lts
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn install --frozen-lockfile
      - run:
          name: Publish to Npm
          command: |
            echo $PATH
      - gh/release:
          title: << pipeline.git.tag >>
          tag: << pipeline.git.tag >>
          context:
              - GITHUB_CREDS
  build-and-deploy-docs:
    docker:
      - image: node:lts
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn install --frozen-lockfile
      - run:
          name: Build Docs
          command: |
            yarn build
      - run:
          name: Deploy Docs to GitHub Pages
          command: |
            echo $PATH

workflows:
  version: 2
  build:
    jobs:
      - publish-to-npm:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build-and-deploy-docs:
          filters:
            branches:
              only: main
